# This target creates a module without servicepoints and ncs:service-data
# groupings.
# Stripped module that is the result of this target is imported in the node
# service where we need a grouping without servicepoints and service-data
# groupings. The original module is imported in the /rfs/router/ where
# servicepoint and service-data is required. With this we workaround the
# limitation which prevents us from augmenting servicepoint in.

# Please define STRIP_TARGET in each individual Makefile

ifeq ($(shell uname -s),Darwin)
  SED=gsed
else
  SED=sed
endif

ifeq "$(shell which $(SED))" ""
$(error $(SED) is not installed)
endif

pre-compile: $(STRIP_TARGET)

# Here are some rewrite rules for adding -stripped to the module name, namespace
# and prefix in the yang file. Rewriting module rule is straight forward. The
# namespace one actually has two cases, one if the .yang file ending is used in
# the namespace, and one if it is not.
yang/%-stripped.yang: BASENAME=$*
yang/%-stripped.yang: yang/%.yang
	$(SED) -E \
	-e '/ncs:service/d' \
	-e '0,/^ *module / s/( *module "?)([^" ]+)("? *\{)/\1\2-stripped\3/' \
	-e '0,/^ +namespace +".*\.yang/ s/( +namespace ")(.+)(\.yang");/\1\2-stripped\3;/' \
	-e '0,/^ +namespace +"/ {/\.yang/! s/( +namespace "?)([^";]+)("?);/\1\2-stripped\3;/}' \
	-e '0,/^ +prefix / s/( +prefix "?)([^";]+)("?);/\1\2-stripped\3;/' \
	-e '/BEGIN_STRIP/,/END_STRIP/d' $< \
	-e '1s/^/\/* This file is autogenerated by package Makefile. Do not edit manually, change the file $(BASENAME).yang instead. *\/\n/' \
	> yang/$(BASENAME)-stripped.yang
